"""Sequence diagrams: a design in sequence-<scenario>.drawio, a scenario in C++.

    input   diagrams/input/sequence-<scenario>.drawio   one scenario, drawn by a person
            impl/                                       the implementation, with the scenario
                                                        in impl/scenarios/<scenario>.cpp
    output  diagrams/output/sequence-<scenario>-design.mmd
            diagrams/output/sequence-<scenario>-implemented.mmd
            diagrams/output/sequence-<scenario>-comparison.drawio
            reports/sequence-<scenario>-report.md

The implemented diagram is not read from the code but recorded from it: the scenario runs in
a build where every function reports its entry and exit, and the calls between the project's
classes are the messages. See docs/SEQUENCE-DIAGRAMS.md and the "Sequence diagrams" section
of docs/UML-CPP-MAPPING.md.
"""
from ..core.project import FlowFailed, NotReady, build_cmake, build_traced
from ..core.report import ReportText, render
from . import drawio_read, drawio_write, elements, mermaid

NAME = "sequence"
SUBJECT = "scenario"
FILE = "sequence-<scenario>.drawio"
TITLE = "Sequence diagram"

TEXT = ReportText(
    title="Sequence diagram verification report",
    columns=elements.COLUMNS,
    element="one lifeline, or one message: a call from one lifeline to another (or to "
            "itself), in order; return arrows are documentation and are not counted",
    details="the caller, the receiver, the method, and the message's place in the sequence",
    implemented_by="recorded by running the scenario in a traced build: every call between "
                   "the project's classes while `scenario()` runs is a message",
    not_counted="Calls a class makes to itself that the design does not draw. A sequence "
                "diagram shows the collaboration between objects; a class's private helpers "
                "are its own business unless the design draws them.",
)


def run(ctx):
    """Verify one scenario. Returns the comparison result; raises FlowFailed or NotReady."""
    scenario = ctx.subject
    design_mmd = ctx.output("design.mmd")
    implemented_mmd = ctx.output("implemented.mmd")
    comparison = ctx.output("comparison.drawio")
    include = ctx.impl / "include"
    source = ctx.impl / "scenarios" / f"{scenario}.cpp"
    generated = "GENERATED by tools/verify.py -- do not edit; edit {} instead."

    ctx.step(1, 4, f"Reading the design, {ctx.show(ctx.input)}")
    design, layout, warnings = drawio_read.read(ctx.input)
    if not design["lifelines"]:
        raise FlowFailed(f"{ctx.show(ctx.input)} contains no lifelines. Is it a sequence diagram "
                         "drawn with draw.io's UML shapes (lifelines, messages)?")
    design_mmd.write_text(mermaid.write(design, header=[generated.format(ctx.show(ctx.input)),
                                                        f"The scenario {scenario}."]))
    calls = sum(1 for m in design["messages"] if m["kind"] == "call")
    ctx.note(f"{len(design['lifelines'])} lifelines, {calls} messages -> {ctx.show(design_mmd)}")
    for w in warnings:
        ctx.note(f"warning: {w}")

    ctx.step(2, 4, f"Building {ctx.show(ctx.impl)}/, with tracing")
    if not (ctx.impl / "CMakeLists.txt").exists():
        raise NotReady(f"no implementation yet — the design was converted to "
                       f"{ctx.show(design_mmd)}; the scenario goes in {ctx.show(source)}")
    build_cmake(ctx)
    if not source.exists():
        raise FlowFailed(f"the implementation has no scenario for this diagram: write "
                         f"{ctx.show(source)} with a scenario() function that makes the drawn "
                         f"calls, and add it to CMakeLists.txt as "
                         f"add_executable(scenario_{scenario} scenarios/{scenario}.cpp)")
    build_traced(ctx)
    executable = next((p for name in (f"scenario_{scenario}", f"scenario_{scenario}.exe")
                       for p in sorted(ctx.trace_build.rglob(name)) if p.is_file()), None)
    if executable is None or not executable.is_file():
        raise FlowFailed(f"the build has no executable scenario_{scenario}; add "
                         f"add_executable(scenario_{scenario} scenarios/{scenario}.cpp) to "
                         f"CMakeLists.txt and link it to the library")
    ctx.note("build OK")

    ctx.step(3, 4, f"Running {ctx.show(source)} and recording its messages")
    try:
        from ..core.cpp import project_classes
        from . import trace_extract
    except ImportError as e:
        raise FlowFailed("the libclang Python bindings are not installed. In VS Code run the "
                         "task 'Set up Python environment', or run these one per line: "
                         "python -m venv .venv, then "
                         ".venv/bin/pip install -r requirements.txt "
                         "(Windows: .venv\\Scripts\\pip install -r requirements.txt)", f"{type(e).__name__}: {e}")
    try:
        classes = project_classes(include)
    except RuntimeError as e:
        raise FlowFailed("libclang could not read the headers", str(e))
    initiator = next(l for l in design["lifelines"] if l["name"] == mermaid.initiator(design))
    try:
        implemented, trace_warnings = trace_extract.extract(
            executable, ctx.trace_build / "traces" / f"{scenario}.txt", classes, initiator)
    except (RuntimeError, OSError) as e:
        raise FlowFailed(f"the scenario could not be traced: {e}")
    implemented_mmd.write_text(mermaid.write(implemented, header=[
        generated.format(ctx.show(source)),
        "The scenario as implemented: the calls recorded while it ran. No AI produced this file.",
        f"The scenario {scenario}."]))
    ctx.note(f"{len(implemented['messages'])} messages -> {ctx.show(implemented_mmd)}")
    for w in trace_warnings:
        ctx.note(f"warning: {w}")
    warnings += trace_warnings

    ctx.step(4, 4, "Comparing")
    result = elements.align(elements.elements(design_mmd.read_text()),
                            elements.elements(implemented_mmd.read_text()))

    sources = {"design": f"{ctx.link(ctx.input)} → {ctx.link(design_mmd)}",
               "implemented": f"{ctx.link(implemented_mmd)}, recorded from {ctx.link(source)}"}
    ctx.report.parent.mkdir(parents=True, exist_ok=True)
    ctx.report.write_text(render(result, TEXT._replace(title=f"{TEXT.title}: {scenario}"),
                                 sources, ctx.href(comparison), warnings))
    comparison.write_text(drawio_write.comparison(
        design_mmd, implemented_mmd, layout, result,
        design_label=f"drawn by a person · {ctx.show(ctx.input)}",
        implemented_label=f"built by AI · recorded from {ctx.show(source)}"))
    return result
