"""Class diagrams: a design in class.drawio, an implementation in C++.

    input   diagrams/input/class.drawio
            impl/                             (CMake project; headers in impl/include/)
    output  diagrams/output/class-design.mmd
            diagrams/output/class-implemented.mmd
            diagrams/output/class-comparison.drawio
            reports/class-report.md

See docs/CLASS-DIAGRAMS.md and docs/UML-CPP-MAPPING.md.
"""
from ..core.compare import compare, totals
from ..core.project import FlowFailed, NotReady, build_cmake
from ..core.report import ReportText, render
from . import drawio_read, drawio_write, elements, mermaid

NAME = "class"
FILE = "class.drawio"
TITLE = "Class diagram"

TEXT = ReportText(
    title="Class diagram verification report",
    columns=elements.COLUMNS,
    element="one class, one attribute (or enum value), one method, or one relation",
    details="types, parameters, visibility, relation kind, cardinality",
    implemented_by="extracted from the C++ headers by libclang",
    not_counted="Dependencies the design already implies through a method signature. "
                "Designs rarely draw these arrows, so finding one in the implementation "
                "is not a difference.",
)


def run(ctx):
    """Verify one project. Returns the comparison result; raises FlowFailed or NotReady."""
    design_mmd = ctx.output("design.mmd")
    implemented_mmd = ctx.output("implemented.mmd")
    comparison = ctx.output("comparison.drawio")
    include = ctx.impl / "include"
    generated = "GENERATED by tools/verify.py -- do not edit; edit {} instead."

    ctx.step(1, 4, f"Reading the design, {ctx.show(ctx.input)}")
    types, relations, layout, warnings = drawio_read.read(ctx.input)
    if not types:
        raise FlowFailed(f"{ctx.show(ctx.input)} contains no class shapes. "
                         "Is it a class diagram drawn with draw.io's UML shapes?")
    design_mmd.write_text(mermaid.write(types, relations,
                                        header=[generated.format(ctx.show(ctx.input))]))
    ctx.note(f"{len(types)} classes, {len(relations)} relations -> {ctx.show(design_mmd)}")
    for w in warnings:
        ctx.note(f"warning: {w}")

    ctx.step(2, 4, f"Building {ctx.show(ctx.impl)}/")
    if not (ctx.impl / "CMakeLists.txt").exists():
        raise NotReady(f"no implementation yet — the design was converted to "
                       f"{ctx.show(design_mmd)}; the implementation goes in "
                       f"{ctx.show(include)}/ (headers), {ctx.show(ctx.impl)}/src/ (sources) "
                       f"and {ctx.show(ctx.impl)}/CMakeLists.txt")
    build_cmake(ctx)
    ctx.note("build OK")

    ctx.step(3, 4, f"Reading the implemented design from {ctx.show(include)}/")
    try:
        from . import cpp_extract
    except ImportError as e:
        raise FlowFailed("the libclang Python bindings are not installed. In VS Code run the "
                         "task 'Set up Python environment', or run these one per line: "
                         "python -m venv .venv, then "
                         ".venv/bin/pip install -r requirements.txt "
                         "(Windows: .venv\\Scripts\\pip install -r requirements.txt)", f"{type(e).__name__}: {e}")
    try:
        extracted = cpp_extract.extract(include)
    except RuntimeError as e:
        raise FlowFailed("libclang could not read the headers", str(e))
    implemented_mmd.write_text(
        f"%% {generated.format(ctx.show(include))}\n"
        "%% The design as implemented: what the compiler sees. No AI produced this file.\n"
        + extracted)
    ctx.note(f"-> {ctx.show(implemented_mmd)}")

    ctx.step(4, 4, "Comparing")
    design, design_types = elements.elements(design_mmd.read_text())
    implemented, _ = elements.elements(implemented_mmd.read_text())
    result = compare(design, implemented, [c for c, _ in elements.COLUMNS],
                     elements.implied_dependencies(design_types))

    sources = {"design": f"{ctx.link(ctx.input)} → {ctx.link(design_mmd)}",
               "implemented": f"{ctx.link(implemented_mmd)}, from {ctx.link(include, ctx.show(include) + '/')}"}
    ctx.report.parent.mkdir(parents=True, exist_ok=True)
    ctx.report.write_text(render(result, TEXT, sources, ctx.href(comparison), warnings))
    comparison.write_text(drawio_write.comparison(
        design_mmd, implemented_mmd, layout, result,
        design_label=f"drawn by a person · {ctx.show(ctx.input)}",
        implemented_label=f"built by AI · extracted from {ctx.show(include)}"))
    return result
