"""State machines: a design in state-<class>.drawio, an implementation in C++.

    input   diagrams/input/state-<class>.drawio       the state machine of one class
            impl/                                     (CMake project; headers in impl/include/)
    output  diagrams/output/state-<class>-design.mmd
            diagrams/output/state-<class>-implemented.mmd
            diagrams/output/state-<class>-comparison.drawio
            reports/state-<class>-report.md

See docs/STATE-DIAGRAMS.md and the "State machines" section of docs/UML-CPP-MAPPING.md.
"""
from ..core.compare import compare
from ..core.project import FlowFailed, NotReady, build_cmake
from ..core.report import ReportText, render
from . import drawio_read, drawio_write, elements, mermaid

NAME = "state"
SUBJECT = "class"
FILE = "state-<class>.drawio"
TITLE = "State machine"

TEXT = ReportText(
    title="State machine verification report",
    columns=elements.COLUMNS,
    element="one state, one event, or one transition (the initial transition `[*] --> S` is one too)",
    details="target state, guard and action; for the initial transition, the state it enters",
    implemented_by="extracted from the C++ headers by libclang: the transition table, "
                   "its State and Event enums, and the state attribute's initializer",
)


def class_name(subject):
    """state-library_item.drawio -> LibraryItem: how the design names its class."""
    return "".join(part[:1].upper() + part[1:] for part in subject.split("_"))


def run(ctx):
    """Verify one state machine. Returns the comparison result; raises FlowFailed or NotReady."""
    subject = class_name(ctx.subject)
    design_mmd = ctx.output("design.mmd")
    implemented_mmd = ctx.output("implemented.mmd")
    comparison = ctx.output("comparison.drawio")
    include = ctx.impl / "include"
    generated = "GENERATED by tools/verify.py -- do not edit; edit {} instead."

    ctx.step(1, 4, f"Reading the design, {ctx.show(ctx.input)}")
    machine, layout, warnings = drawio_read.read(ctx.input)
    if not machine["states"]:
        raise FlowFailed(f"{ctx.show(ctx.input)} contains no state shapes. Is it a state machine "
                         "drawn with draw.io's UML shapes (rounded-rectangle states, a start symbol)?")
    design_mmd.write_text(mermaid.write(machine, header=[generated.format(ctx.show(ctx.input)),
                                                         f"The state machine of {subject}."]))
    ctx.note(f"{len(machine['states'])} states, {len(machine['transitions'])} transitions "
             f"-> {ctx.show(design_mmd)}")
    for w in warnings:
        ctx.note(f"warning: {w}")

    ctx.step(2, 4, f"Building {ctx.show(ctx.impl)}/")
    if not (ctx.impl / "CMakeLists.txt").exists():
        raise NotReady(f"no implementation yet — the design was converted to "
                       f"{ctx.show(design_mmd)}; the implementation goes in "
                       f"{ctx.show(include)}/ (headers), {ctx.show(ctx.impl)}/src/ (sources) "
                       f"and {ctx.show(ctx.impl)}/CMakeLists.txt")
    build_cmake(ctx)
    ctx.note("build OK")

    ctx.step(3, 4, f"Reading the implemented state machine of {subject} from {ctx.show(include)}/")
    try:
        from . import cpp_extract
    except ImportError as e:
        raise FlowFailed("the libclang Python bindings are not installed. In VS Code run the "
                         "task 'Set up Python environment', or run these one per line: "
                         "python -m venv .venv, then "
                         ".venv/bin/pip install -r requirements.txt "
                         "(Windows: .venv\\Scripts\\pip install -r requirements.txt)", f"{type(e).__name__}: {e}")
    try:
        implemented, found, extract_warnings = cpp_extract.extract(include, subject)
    except RuntimeError as e:
        raise FlowFailed("libclang could not read the headers", str(e))
    name = found or subject
    implemented_mmd.write_text(mermaid.write(implemented, header=[
        generated.format(ctx.show(include)),
        "The state machine as implemented: what the compiler sees. No AI produced this file.",
        f"The state machine of {name}."]))
    ctx.note(f"-> {ctx.show(implemented_mmd)}")
    for w in extract_warnings:
        ctx.note(f"warning: {w}")
    warnings += extract_warnings

    ctx.step(4, 4, "Comparing")
    design, _ = elements.elements(design_mmd.read_text())
    implemented_elements, _ = elements.elements(implemented_mmd.read_text())
    result = compare(design, implemented_elements, [c for c, _ in elements.COLUMNS])

    sources = {"design": f"{ctx.link(ctx.input)} → {ctx.link(design_mmd)}",
               "implemented": f"{ctx.link(implemented_mmd)}, from {ctx.link(include, ctx.show(include) + '/')}"}
    ctx.report.parent.mkdir(parents=True, exist_ok=True)
    ctx.report.write_text(render(result, TEXT._replace(title=f"{TEXT.title}: {name}"),
                                 sources, ctx.href(comparison), warnings))
    comparison.write_text(drawio_write.comparison(
        design_mmd, implemented_mmd, layout, result,
        design_label=f"drawn by a person · {ctx.show(ctx.input)}",
        implemented_label=f"built by AI · extracted from {ctx.show(include)}"))
    return result
